#!/bin/bash
clang int32.c \
  --target=wasm32-unknown-unknown-wasm \
  --optimize=3 \
  -nostdlib \
  -Wl,--export-all \
  -Wl,--no-entry \
  -Wl,--allow-undefined \
  -I /usr/include \
  --output int32.wasm

# 也可以使用 emcc 来编译
# em++ -std=c++11 -o int32.wasm int32.c -O3 -s WASM=1 -s SIDE_MODULE=1 -s NO_EXIT_RUNTIME=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']"
# emcc -std=c11 -o int32.wasm int32.c -O3 -s WASM=1 -s SIDE_MODULE=1

# 可以转换 WASM 为文本格式（供阅读、检查）
# wasm2wat int64.wasm

# 输出 WASM 二进制文件为 hex 字符串
#hexdump int32.wasm -ve '1/1 "%02x"' > int32.wasm.hex
#hexdump int32.wasm -ve '1/1 "%02x"' | fold -w 80 > int32.wasm.hex

hexdump int32.wasm -ve '1/1 "%02x"'| \
fold -w 80 | \
awk '{ print "\""$0"\"+"}'